import type { LucideIcon } from 'lucide-react';
import {
  ArrowLeftRight,
  ArrowUpDown,
  Award,
  Bell,
  Bold,
  Book,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Check,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleDollarSign,
  CircleStar,
  Clock,
  Code,
  Copy,
  CornerUpLeft,
  CupSoda,
  Ellipsis,
  ExternalLink,
  EyeOff,
  FileText,
  Flag,
  Globe,
  Hand,
  HandHelping,
  Hash,
  Heart,
  Image,
  Info,
  Italic,
  Landmark,
  LayoutGrid,
  Link,
  List,
  ListFilter,
  LocateFixed,
  Lock,
  LockOpen,
  Mail,
  Map,
  MapPin,
  Maximize2,
  MessageSquare,
  Minimize2,
  Minus,
  Package,
  Pencil,
  PenLine,
  Phone,
  Pin,
  Play,
  Plus,
  Puzzle,
  QrCode,
  Repeat2,
  Rss,
  RulerDimensionLine,
  Search,
  Send,
  Share2,
  SendHorizontal,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Store,
  Table,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingUp,
  User,
  UserMinus,
  Utensils,
  UtensilsCrossed,
  UserPlus,
  Users,
  Video,
  VolumeX,
  Wallet,
  Weight,
  X,
  Zap,
} from 'lucide-react';

import { ICON_SIZE, resolveIconSize } from '../../constants';
import type { IconComponent, IconComponentProps } from '../../types';

export function createLucideIcon(LucideGlyph: LucideIcon): IconComponent {
  return function LucideIconWrapper({
    size,
    className,
    strokeWidth,
    title,
  }: IconComponentProps) {
    const px = resolveIconSize(size);
    if (title) {
      return (
        <LucideGlyph
          size={px}
          className={className}
          strokeWidth={strokeWidth}
          role="img"
          aria-hidden={undefined}
        >
          <title>{title}</title>
        </LucideGlyph>
      );
    }

    return (
      <LucideGlyph
        size={px}
        className={className}
        strokeWidth={strokeWidth}
        aria-hidden
      />
    );
  };
}

export const lucideIconPack = {
  'arrow-left-right': createLucideIcon(ArrowLeftRight),
  'arrow-up-down': createLucideIcon(ArrowUpDown),
  award: createLucideIcon(Award),
  bell: createLucideIcon(Bell),
  bold: createLucideIcon(Bold),
  book: createLucideIcon(Book),
  'book-open': createLucideIcon(BookOpen),
  briefcase: createLucideIcon(Briefcase),
  building: createLucideIcon(Building2),
  calendar: createLucideIcon(Calendar),
  check: createLucideIcon(Check),
  'check-circle': createLucideIcon(CircleCheck),
  'chef-hat': createLucideIcon(ChefHat),
  'circle-star': createLucideIcon(CircleStar),
  'chevron-down': createLucideIcon(ChevronDown),
  'chevron-left': createLucideIcon(ChevronLeft),
  'chevron-right': createLucideIcon(ChevronRight),
  clock: createLucideIcon(Clock),
  close: createLucideIcon(X),
  code: createLucideIcon(Code),
  comment: createLucideIcon(MessageSquare),
  copy: createLucideIcon(Copy),
  'cup-soda': createLucideIcon(CupSoda),
  dollar: createLucideIcon(CircleDollarSign),
  emoji: createLucideIcon(Smile),
  'external-link': createLucideIcon(ExternalLink),
  'eye-off': createLucideIcon(EyeOff),
  'file-text': createLucideIcon(FileText),
  filter: createLucideIcon(ListFilter),
  flag: createLucideIcon(Flag),
  globe: createLucideIcon(Globe),
  hand: createLucideIcon(Hand),
  'hand-helping': createLucideIcon(HandHelping),
  hash: createLucideIcon(Hash),
  heart: createLucideIcon(Heart),
  image: createLucideIcon(Image),
  info: createLucideIcon(Info),
  italic: createLucideIcon(Italic),
  landmark: createLucideIcon(Landmark),
  'layout-grid': createLucideIcon(LayoutGrid),
  link: createLucideIcon(Link),
  list: createLucideIcon(List),
  locate: createLucideIcon(LocateFixed),
  lock: createLucideIcon(Lock),
  'lock-open': createLucideIcon(LockOpen),
  mail: createLucideIcon(Mail),
  map: createLucideIcon(Map),
  'map-pin': createLucideIcon(MapPin),
  maximize: createLucideIcon(Maximize2),
  minimize: createLucideIcon(Minimize2),
  minus: createLucideIcon(Minus),
  'more-horizontal': createLucideIcon(Ellipsis),
  package: createLucideIcon(Package),
  mute: createLucideIcon(VolumeX),
  pencil: createLucideIcon(Pencil),
  'pen-line': createLucideIcon(PenLine),
  phone: createLucideIcon(Phone),
  pin: createLucideIcon(Pin),
  play: createLucideIcon(Play),
  plus: createLucideIcon(Plus),
  puzzle: createLucideIcon(Puzzle),
  'qr-code': createLucideIcon(QrCode),
  reblog: createLucideIcon(Repeat2),
  rss: createLucideIcon(Rss),
  reply: createLucideIcon(CornerUpLeft),
  'ruler-dimension-line': createLucideIcon(RulerDimensionLine),
  search: createLucideIcon(Search),
  share: createLucideIcon(Share2),
  send: createLucideIcon(Send),
  'send-horizontal': createLucideIcon(SendHorizontal),
  'shopping-bag': createLucideIcon(ShoppingBag),
  'shopping-cart': createLucideIcon(ShoppingCart),
  smartphone: createLucideIcon(Smartphone),
  sparkles: createLucideIcon(Sparkles),
  star: createLucideIcon(Star),
  store: createLucideIcon(Store),
  table: createLucideIcon(Table),
  'thumb-down': createLucideIcon(ThumbsDown),
  'thumb-up': createLucideIcon(ThumbsUp),
  trash: createLucideIcon(Trash2),
  'trending-up': createLucideIcon(TrendingUp),
  user: createLucideIcon(User),
  utensils: createLucideIcon(Utensils),
  'utensils-crossed': createLucideIcon(UtensilsCrossed),
  'user-minus': createLucideIcon(UserMinus),
  'user-plus': createLucideIcon(UserPlus),
  users: createLucideIcon(Users),
  video: createLucideIcon(Video),
  wallet: createLucideIcon(Wallet),
  weight: createLucideIcon(Weight),
  zap: createLucideIcon(Zap),
} as const satisfies Record<string, IconComponent>;

export type LucideIconName = keyof typeof lucideIconPack;

/** Default pixel size re-export for callers that need explicit dimensions. */
export { ICON_SIZE };
