import type { UpdateRegistry } from './types';
import { UPDATE_TYPES } from './update-types';
import { UPDATE_NAME } from './name';
import { UPDATE_OPTIONS } from './options';
import { UPDATE_AGE_RANGE } from './age-range';
import { UPDATE_PUBLICATION_DATE } from './publication-date';
import { UPDATE_GROUP_ID } from './group-id';
import { UPDATE_IDENTIFIER } from './identifier';
import { UPDATE_PRODUCT_WEIGHT } from './weight';
import { UPDATE_DIMENSIONS } from './dimensions';
import { UPDATE_AUTHORS } from './authors';
import { UPDATE_PUBLISHER } from './publisher';
import { UPDATE_PRINT_LENGTH } from './print-length';
import { UPDATE_NEWS_FEED } from './news-feed';
import { UPDATE_WIDGET } from './widget';
import { UPDATE_MERCHANT } from './merchant';
import { UPDATE_MANUFACTURER } from './manufacturer';
import { UPDATE_BRAND } from './brand';
import { UPDATE_FEATURES } from './features';
import { UPDATE_RELATED } from './related';
import { UPDATE_ADD_ON } from './add-on';
import { UPDATE_SIMILAR } from './similar';
import { UPDATE_PIN } from './pin';
import { UPDATE_REMOVE } from './remove';
import { UPDATE_SHOP_FILTER } from './shop-filter';
import { UPDATE_MENU_ITEM } from './menu-item';
import { UPDATE_AFFILIATE_BUTTON } from './affiliate-button';
import { UPDATE_AFFILIATE_PRODUCT_ID_TYPES } from './affiliate-product-id-types';
import { UPDATE_AFFILIATE_GEO_AREA } from './affiliate-geo-area';
import { UPDATE_AFFILIATE_URL_TEMPLATE } from './affiliate-url-template';
import { UPDATE_AFFILIATE_CODE } from './affiliate-code';
import { UPDATE_MAP } from './map';
import { UPDATE_MAP_OBJECT_TYPES } from './map-object-types';
import { UPDATE_MAP_OBJECT_TAGS } from './map-object-tags';
import { UPDATE_MAP_MOBILE_VIEW } from './map-mobile-view';
import { UPDATE_MAP_DESKTOP_VIEW } from './map-desktop-view';
import { UPDATE_MAP_RECTANGLES } from './map-rectangles';
import { UPDATE_MAP_OBJECTS_LIST } from './map-objects-list';
import { UPDATE_WALLET_ADDRESS } from './wallet-address';
import { UPDATE_DELEGATION } from './delegation';
import { UPDATE_URL } from './url';
import { UPDATE_CALORIES } from './calories';
import { UPDATE_BUDGET } from './budget';
import { UPDATE_COOKING_TIME } from './cooking-time';
import { UPDATE_COST } from './cost';
import { UPDATE_RECIPE_INGREDIENTS } from './recipe-ingredients';
import { UPDATE_GROUP_EXPERTISE } from './group-expertise';
import { UPDATE_GROUP_FOLLOWERS } from './group-followers';
import { UPDATE_GROUP_FOLLOWING } from './group-following';
import { UPDATE_GROUP_ADD } from './group-add';
import { UPDATE_GROUP_EXCLUDE } from './group-exclude';
import { UPDATE_GROUP_LAST_ACTIVITY } from './group-last-activity';
import { UPDATE_GROUP_MIN_EXPERTISE } from './group-min-expertise';
import { UPDATE_PROMOTION } from './promotion';
import { UPDATE_NUTRITION } from './nutrition';
import { UPDATE_FEATURED } from './featured';
import { UPDATE_SALE } from './sale';
import { UPDATE_COMPARE_AT_PRICE } from './compare-at-price';
import { UPDATE_CONTENT_POSITION } from './content-position';
import { UPDATE_HTML_CONTENT } from './html-content';
import { UPDATE_CONTENT_VIEW } from './content-view';
import { UPDATE_STATUS } from './status';
import { UPDATE_AVATAR } from './avatar';
import { UPDATE_TITLE } from './title';
import { UPDATE_DESCRIPTION } from './description';
import { UPDATE_BACKGROUND } from './background';
import { UPDATE_TAG_CATEGORY } from './tag-category';
import { UPDATE_CATEGORY_ITEM } from './category-item';
import { UPDATE_GALLERY_ALBUM } from './gallery-album';
import { UPDATE_GALLERY_ITEM } from './gallery-item';
import { UPDATE_PARENT } from './parent';
import { UPDATE_LANGUAGE } from './language';
import { UPDATE_DEPARTMENTS } from './departments';
import { UPDATE_WEBSITE } from './website';
import { UPDATE_RATING } from './rating';
import { UPDATE_LIST_ITEM } from './list-item';
import { UPDATE_PRICE } from './price';
import { UPDATE_SORT_CUSTOM } from './sort-custom';
import { UPDATE_ADDRESS } from './address';
import { UPDATE_FORM } from './form';
import { UPDATE_BLOG } from './blog';
import { UPDATE_NEWS_FILTER } from './news-filter';
import { UPDATE_WORK_TIME } from './work-time';
import { UPDATE_BUTTON } from './button';
import { UPDATE_PHONE } from './phone';
import { UPDATE_LINK } from './link';
import { UPDATE_EMAIL } from './email';
import { UPDATE_CHART_ID } from './chartid';
import { UPDATE_PAGE_CONTENT } from './page-content';

export const UPDATE_REGISTRY = {
  [UPDATE_TYPES.NAME]: UPDATE_NAME,
  [UPDATE_TYPES.OPTIONS]: UPDATE_OPTIONS,
  [UPDATE_TYPES.AGE_RANGE]: UPDATE_AGE_RANGE,
  [UPDATE_TYPES.PUBLICATION_DATE]: UPDATE_PUBLICATION_DATE,
  [UPDATE_TYPES.GROUP_ID]: UPDATE_GROUP_ID,
  [UPDATE_TYPES.IDENTIFIER]: UPDATE_IDENTIFIER,
  [UPDATE_TYPES.PRODUCT_WEIGHT]: UPDATE_PRODUCT_WEIGHT,
  [UPDATE_TYPES.DIMENSIONS]: UPDATE_DIMENSIONS,
  [UPDATE_TYPES.AUTHORS]: UPDATE_AUTHORS,
  [UPDATE_TYPES.PUBLISHER]: UPDATE_PUBLISHER,
  [UPDATE_TYPES.PRINT_LENGTH]: UPDATE_PRINT_LENGTH,
  [UPDATE_TYPES.NEWS_FEED]: UPDATE_NEWS_FEED,
  [UPDATE_TYPES.WIDGET]: UPDATE_WIDGET,
  [UPDATE_TYPES.MERCHANT]: UPDATE_MERCHANT,
  [UPDATE_TYPES.MANUFACTURER]: UPDATE_MANUFACTURER,
  [UPDATE_TYPES.BRAND]: UPDATE_BRAND,
  [UPDATE_TYPES.FEATURES]: UPDATE_FEATURES,
  [UPDATE_TYPES.RELATED]: UPDATE_RELATED,
  [UPDATE_TYPES.ADD_ON]: UPDATE_ADD_ON,
  [UPDATE_TYPES.SIMILAR]: UPDATE_SIMILAR,
  [UPDATE_TYPES.PIN]: UPDATE_PIN,
  [UPDATE_TYPES.REMOVE]: UPDATE_REMOVE,
  [UPDATE_TYPES.SHOP_FILTER]: UPDATE_SHOP_FILTER,
  [UPDATE_TYPES.MENU_ITEM]: UPDATE_MENU_ITEM,
  [UPDATE_TYPES.AFFILIATE_BUTTON]: UPDATE_AFFILIATE_BUTTON,
  [UPDATE_TYPES.AFFILIATE_PRODUCT_ID_TYPES]: UPDATE_AFFILIATE_PRODUCT_ID_TYPES,
  [UPDATE_TYPES.AFFILIATE_GEO_AREA]: UPDATE_AFFILIATE_GEO_AREA,
  [UPDATE_TYPES.AFFILIATE_URL_TEMPLATE]: UPDATE_AFFILIATE_URL_TEMPLATE,
  [UPDATE_TYPES.AFFILIATE_CODE]: UPDATE_AFFILIATE_CODE,
  [UPDATE_TYPES.MAP]: UPDATE_MAP,
  [UPDATE_TYPES.MAP_OBJECT_TYPES]: UPDATE_MAP_OBJECT_TYPES,
  [UPDATE_TYPES.MAP_OBJECT_TAGS]: UPDATE_MAP_OBJECT_TAGS,
  [UPDATE_TYPES.MAP_MOBILE_VIEW]: UPDATE_MAP_MOBILE_VIEW,
  [UPDATE_TYPES.MAP_DESKTOP_VIEW]: UPDATE_MAP_DESKTOP_VIEW,
  [UPDATE_TYPES.MAP_RECTANGLES]: UPDATE_MAP_RECTANGLES,
  [UPDATE_TYPES.MAP_OBJECTS_LIST]: UPDATE_MAP_OBJECTS_LIST,
  [UPDATE_TYPES.WALLET_ADDRESS]: UPDATE_WALLET_ADDRESS,
  [UPDATE_TYPES.DELEGATION]: UPDATE_DELEGATION,
  [UPDATE_TYPES.URL]: UPDATE_URL,
  [UPDATE_TYPES.CALORIES]: UPDATE_CALORIES,
  [UPDATE_TYPES.BUDGET]: UPDATE_BUDGET,
  [UPDATE_TYPES.COOKING_TIME]: UPDATE_COOKING_TIME,
  [UPDATE_TYPES.COST]: UPDATE_COST,
  [UPDATE_TYPES.RECIPE_INGREDIENTS]: UPDATE_RECIPE_INGREDIENTS,
  [UPDATE_TYPES.GROUP_EXPERTISE]: UPDATE_GROUP_EXPERTISE,
  [UPDATE_TYPES.GROUP_FOLLOWERS]: UPDATE_GROUP_FOLLOWERS,
  [UPDATE_TYPES.GROUP_FOLLOWING]: UPDATE_GROUP_FOLLOWING,
  [UPDATE_TYPES.GROUP_ADD]: UPDATE_GROUP_ADD,
  [UPDATE_TYPES.GROUP_EXCLUDE]: UPDATE_GROUP_EXCLUDE,
  [UPDATE_TYPES.GROUP_LAST_ACTIVITY]: UPDATE_GROUP_LAST_ACTIVITY,
  [UPDATE_TYPES.GROUP_MIN_EXPERTISE]: UPDATE_GROUP_MIN_EXPERTISE,
  [UPDATE_TYPES.PROMOTION]: UPDATE_PROMOTION,
  [UPDATE_TYPES.NUTRITION]: UPDATE_NUTRITION,
  [UPDATE_TYPES.FEATURED]: UPDATE_FEATURED,
  [UPDATE_TYPES.SALE]: UPDATE_SALE,
  [UPDATE_TYPES.COMPARE_AT_PRICE]: UPDATE_COMPARE_AT_PRICE,
  [UPDATE_TYPES.CONTENT_POSITION]: UPDATE_CONTENT_POSITION,
  [UPDATE_TYPES.HTML_CONTENT]: UPDATE_HTML_CONTENT,
  [UPDATE_TYPES.CONTENT_VIEW]: UPDATE_CONTENT_VIEW,
  [UPDATE_TYPES.STATUS]: UPDATE_STATUS,
  [UPDATE_TYPES.AVATAR]: UPDATE_AVATAR,
  [UPDATE_TYPES.TITLE]: UPDATE_TITLE,
  [UPDATE_TYPES.DESCRIPTION]: UPDATE_DESCRIPTION,
  [UPDATE_TYPES.BACKGROUND]: UPDATE_BACKGROUND,
  [UPDATE_TYPES.TAG_CATEGORY]: UPDATE_TAG_CATEGORY,
  [UPDATE_TYPES.CATEGORY_ITEM]: UPDATE_CATEGORY_ITEM,
  [UPDATE_TYPES.GALLERY_ALBUM]: UPDATE_GALLERY_ALBUM,
  [UPDATE_TYPES.GALLERY_ITEM]: UPDATE_GALLERY_ITEM,
  [UPDATE_TYPES.PARENT]: UPDATE_PARENT,
  [UPDATE_TYPES.LANGUAGE]: UPDATE_LANGUAGE,
  [UPDATE_TYPES.DEPARTMENTS]: UPDATE_DEPARTMENTS,
  [UPDATE_TYPES.WEBSITE]: UPDATE_WEBSITE,
  [UPDATE_TYPES.RATING]: UPDATE_RATING,
  [UPDATE_TYPES.LIST_ITEM]: UPDATE_LIST_ITEM,
  [UPDATE_TYPES.PRICE]: UPDATE_PRICE,
  [UPDATE_TYPES.SORT_CUSTOM]: UPDATE_SORT_CUSTOM,
  [UPDATE_TYPES.ADDRESS]: UPDATE_ADDRESS,
  [UPDATE_TYPES.FORM]: UPDATE_FORM,
  [UPDATE_TYPES.BLOG]: UPDATE_BLOG,
  [UPDATE_TYPES.NEWS_FILTER]: UPDATE_NEWS_FILTER,
  [UPDATE_TYPES.WORK_TIME]: UPDATE_WORK_TIME,
  [UPDATE_TYPES.BUTTON]: UPDATE_BUTTON,
  [UPDATE_TYPES.PHONE]: UPDATE_PHONE,
  [UPDATE_TYPES.LINK]: UPDATE_LINK,
  [UPDATE_TYPES.EMAIL]: UPDATE_EMAIL,
  [UPDATE_TYPES.CHART_ID]: UPDATE_CHART_ID,
  [UPDATE_TYPES.PAGE_CONTENT]: UPDATE_PAGE_CONTENT,
} satisfies UpdateRegistry;
