/**
 * String constants for every registered update_type.
 * Use these instead of raw strings when referencing update types in code.
 * @see docs/spec/object-type-entity.md §3
 */
export const UPDATE_TYPES = {
  NAME: 'name',
  OPTION: 'option',
  TYPICAL_AGE_RANGE: 'typicalAgeRange',
  DATE_PUBLISHED: 'datePublished',
  PRODUCT_GROUP_ID: 'productGroupId',
  IDENTIFIER: 'identifier',
  PRODUCT_WEIGHT: 'productWeight',
  SIZE: 'size',
  AUTHOR: 'author',
  PUBLISHER: 'publisher',
  PRINT_LENGTH: 'printLength',
  NEWS_FEED: 'newsFeed',
  WIDGET: 'widget',
  MERCHANT: 'merchant',
  MANUFACTURER: 'manufacturer',
  BRAND: 'brand',
  FEATURE_LIST: 'featureList',
  IS_RELATED_TO: 'isRelatedTo',
  ADD_ON: 'addOn',
  IS_SIMILAR_TO: 'isSimilarTo',
  PIN: 'pin',
  REMOVE: 'remove',
  SHOP_FILTER: 'shopFilter',
  MENU_ITEM: 'menuItem',
  AFFILIATE_BUTTON: 'affiliateButton',
  AFFILIATE_PRODUCT_ID_TYPES: 'affiliateProductIdTypes',
  AFFILIATE_GEO_AREA: 'affiliateGeoArea',
  AFFILIATE_URL_TEMPLATE: 'affiliateUrlTemplate',
  AFFILIATE_CODE: 'affiliateCode',
  GEO: 'geo',
  MAP_OBJECT_TYPES: 'mapObjectTypes',
  MAP_OBJECT_TAGS: 'mapObjectTags',
  MAP_MOBILE_VIEW: 'mapMobileView',
  MAP_DESKTOP_VIEW: 'mapDesktopView',
  MAP_RECTANGLES: 'mapRectangles',
  MAP_OBJECTS_LIST: 'mapObjectsList',
  WALLET_ADDRESS: 'walletAddress',
  DELEGATION: 'delegation',
  URL: 'url',
  CALORIES: 'calories',
  BUDGET: 'budget',
  COOK_TIME: 'cookTime',
  INGREDIENTS: 'ingredients',
  GROUP_EXPERTISE: 'groupExpertise',
  GROUP_FOLLOWERS: 'groupFollowers',
  GROUP_FOLLOWING: 'groupFollowing',
  GROUP_ADD: 'groupAdd',
  GROUP_EXCLUDE: 'groupExclude',
  GROUP_LAST_ACTIVITY: 'groupLastActivity',
  GROUP_MIN_EXPERTISE: 'groupMinExpertise',
  PROMOTION: 'promotion',
  NUTRITION: 'nutrition',
  FEATURED: 'featured',
  SALE_EVENT: 'saleEvent',
  COMPARE_AT_PRICE: 'compareAtPrice',
  CONTENT_POSITION: 'contentPosition',
  HTML_CONTENT: 'htmlContent',
  CONTENT_VIEW: 'contentView',
  STATUS: 'status',
  IMAGE: 'image',
  TITLE: 'title',
  DESCRIPTION: 'description',
  IMAGE_BACKGROUND: 'imageBackground',
  TAG_CATEGORY: 'tagCategory',
  TAG_CATEGORY_ITEM: 'tagCategoryItem',
  IMAGE_GALLERY: 'imageGallery',
  IMAGE_GALLERY_ITEM: 'imageGalleryItem',
  PARENT: 'parent',
  IN_LANGUAGE: 'inLanguage',
  CATEGORY: 'category',
  WEBSITE: 'website',
  AGGREGATE_RATING: 'aggregateRating',
  LIST_ITEM: 'listItem',
  PRICE: 'price',
  SORT_CUSTOM: 'sortCustom',
  ADDRESS: 'address',
  FORM: 'form',
  NEWS_FILTER: 'newsFilter',
  WORK_HOURS: 'workHours',
  BUTTON: 'button',
  TELEPHONE: 'telephone',
  LINK: 'link',
  EMAIL: 'email',
  PAGE_CONTENT: 'pageContent',
  // Governance (docs/spec/governance-resolution.md §2)
  ADMINS: 'admins',
  TRUSTED: 'trusted',
  MODERATORS: 'moderators',
  AUTHORITIES: 'authorities',
  RESTRICTED: 'restricted',
  BANNED: 'banned',
  WHITELIST: 'whitelist',
  OBJECT_CONTROL: 'objectControl',
  INHERITS_FROM: 'inheritsFrom',
  VALIDITY_CUTOFF: 'validityCutoff',
} as const;

export type UpdateType = (typeof UPDATE_TYPES)[keyof typeof UPDATE_TYPES];
