/**
 * String constants for every registered update_type.
 * Use these instead of raw strings when referencing update types in code.
 * @see spec/object-type-entity.md §3
 */
export const UPDATE_TYPES = {
  NAME: 'name',
  OPTIONS: 'options',
  AGE_RANGE: 'age_range',
  PUBLICATION_DATE: 'publication_date',
  GROUP_ID: 'group_id',
  IDENTIFIER: 'identifier',
  WEIGHT: 'weight',
  DIMENSIONS: 'dimensions',
  AUTHORS: 'authors',
  PUBLISHER: 'publisher',
  PRINT_LENGTH: 'print_length',
  NEWS_FEED: 'news_feed',
  WIDGET: 'widget',
  MERCHANT: 'merchant',
  MANUFACTURER: 'manufacturer',
  BRAND: 'brand',
  FEATURES: 'features',
  RELATED: 'related',
  ADD_ON: 'add_on',
  SIMILAR: 'similar',
  PIN: 'pin',
  REMOVE: 'remove',
  SHOP_FILTER: 'shop_filter',
  MENU_ITEM: 'menu_item',
  AFFILIATE_BUTTON: 'affiliate_button',
  AFFILIATE_PRODUCT_ID_TYPES: 'affiliate_product_id_types',
  AFFILIATE_GEO_AREA: 'affiliate_geo_area',
  AFFILIATE_URL_TEMPLATE: 'affiliate_url_template',
  AFFILIATE_CODE: 'affiliate_code',
  MAP_OBJECT_TYPES: 'map_object_types',
  MAP_OBJECT_TAGS: 'map_object_tags',
  MAP_MOBILE_VIEW: 'map_mobile_view',
  MAP_DESKTOP_VIEW: 'map_desktop_view',
  MAP_RECTANGLES: 'map_rectangles',
  MAP_OBJECTS_LIST: 'map_objects_list',
  WALLET_ADDRESS: 'wallet_address',
  DELEGATION: 'delegation',
  URL: 'url',
  CALORIES: 'calories',
  BUDGET: 'budget',
  COOKING_TIME: 'cooking_time',
  COST: 'cost',
  RECIPE_INGREDIENTS: 'recipe_ingredients',
  GROUP_EXPERTISE: 'group_expertise',
  GROUP_FOLLOWERS: 'group_followers',
  GROUP_FOLLOWING: 'group_following',
  GROUP_ADD: 'group_add',
  GROUP_EXCLUDE: 'group_exclude',
  GROUP_LAST_ACTIVITY: 'group_last_activity',
  GROUP_MIN_EXPERTISE: 'group_min_expertise',
  PROMOTION: 'promotion',
  NUTRITION: 'nutrition',
  FEATURED: 'featured',
  SALE: 'sale',
  COMPARE_AT_PRICE: 'compare_at_price',
  CONTENT_POSITION: 'content_position',
  HTML_CONTENT: 'html_content',
  CONTENT_VIEW: 'content_view',
} as const;

export type UpdateType = (typeof UPDATE_TYPES)[keyof typeof UPDATE_TYPES];
