export const OBJECT_TYPES = {
  HASHTAG: 'hashtag',
  LIST: 'list',
  PRODUCT: 'product',
  DRINK: 'drink',
  PLACE: 'place',
  BUSINESS: 'business',
  PAGE: 'page',
  SERVICE: 'service',
  PERSON: 'person',
  RESTAURANT: 'restaurant',
  DISH: 'dish',
  BOOK: 'book',
  WIDGET: 'widget',
  NEWSFEED: 'newsfeed',
  SHOP: 'shop',
  AFFILIATE: 'affiliate',
  WEBPAGE: 'webpage',
  MAP: 'map',
  LINK: 'link',
  RECIPE: 'recipe',
  GROUP: 'group',
  HTML: 'html',
  GOVERNANCE: 'governance',
} as const;

export type ObjectType = (typeof OBJECT_TYPES)[keyof typeof OBJECT_TYPES];