import './global.css';

import { isRTL } from '../i18n/domain/is-rtl';
import { I18nProvider } from '../i18n/providers/i18n-provider';
import { getRequestLocale } from '../i18n/runtime/get-request-locale';
import { loadMessages } from '../i18n/runtime/load-messages';
import { ShellModeProvider } from '@/shell-mode';
import { getServerShellModeResolution } from '@/shell-mode/server';
import { getServerThemeResolution } from '../theme/get-server-theme-resolution';
import { ThemeProvider } from '../theme/theme-provider';
import { ThemeScript } from '../theme/theme-script';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getRequestLocale();
  const messages = await loadMessages(locale);
  const dir = isRTL(locale) ? 'rtl' : 'ltr';
  const themeResolution = await getServerThemeResolution();
  const shellModeResolution = await getServerShellModeResolution();
  const isSystemPreference = themeResolution.preference === 'system';

  return (
    <html
      lang={locale}
      dir={dir}
      suppressHydrationWarning
      {...(!isSystemPreference
        ? { 'data-theme': themeResolution.resolvedTheme }
        : {})}
      data-shell-mode={shellModeResolution.resolvedMode}
    >
      <head>
        {isSystemPreference ? <ThemeScript /> : null}
      </head>
      <body className="min-h-screen bg-bg text-fg antialiased">
        <ThemeProvider initialResolution={themeResolution}>
          <ShellModeProvider initialResolution={shellModeResolution}>
            <I18nProvider locale={locale} messages={messages}>
              {children}
            </I18nProvider>
          </ShellModeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
