import './global.css';

import { isRTL } from '../i18n/domain/is-rtl';
import { I18nProvider } from '../i18n/providers/i18n-provider';
import { getRequestLocale } from '../i18n/runtime/get-request-locale';
import { loadMessages } from '../i18n/runtime/load-messages';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getRequestLocale();
  const messages = await loadMessages(locale);
  const dir = isRTL(locale) ? 'rtl' : 'ltr';

  return (
    <html lang={locale} dir={dir}>
      <body>
        <I18nProvider locale={locale} messages={messages}>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
