import { UPDATE_TYPES } from '@opden-data-layer/core';

/** Update types loaded when resolving a governance object view. */
export const GOVERNANCE_UPDATE_TYPES: string[] = [
  UPDATE_TYPES.ADMINS,
  UPDATE_TYPES.TRUSTED,
  UPDATE_TYPES.MODERATORS,
  UPDATE_TYPES.AUTHORITIES,
  UPDATE_TYPES.RESTRICTED,
  UPDATE_TYPES.BANNED,
  UPDATE_TYPES.WHITELIST,
  UPDATE_TYPES.OBJECT_CONTROL,
  UPDATE_TYPES.INHERITS_FROM,
  UPDATE_TYPES.VALIDITY_CUTOFF,
];
