import { UPDATE_TYPES } from '../update-registry/update-types';
import { OBJECT_TYPES } from './object-types';
import { ObjectTypeDefinition } from './types';

export const BUSINESS_OBJECT_TYPE: ObjectTypeDefinition = {
  object_type: OBJECT_TYPES.BUSINESS,
  supported_updates: [
    UPDATE_TYPES.STATUS,
    UPDATE_TYPES.AVATAR,
    UPDATE_TYPES.NAME,
    UPDATE_TYPES.TITLE,
    UPDATE_TYPES.BACKGROUND,
    UPDATE_TYPES.PARENT,
    UPDATE_TYPES.TAG_CATEGORY,
    UPDATE_TYPES.CATEGORY_ITEM,
    UPDATE_TYPES.GALLERY_ALBUM,
    UPDATE_TYPES.GALLERY_ITEM,
    UPDATE_TYPES.LIST_ITEM,
    UPDATE_TYPES.BUTTON,
    UPDATE_TYPES.NEWS_FILTER,
    UPDATE_TYPES.SORT_CUSTOM,
    UPDATE_TYPES.RATING,
    UPDATE_TYPES.PRICE,
    UPDATE_TYPES.DESCRIPTION,
    UPDATE_TYPES.WORK_TIME,
    UPDATE_TYPES.ADDRESS,
    UPDATE_TYPES.MAP,
    UPDATE_TYPES.WEBSITE,
    UPDATE_TYPES.PHONE,
    UPDATE_TYPES.EMAIL,
    UPDATE_TYPES.LINK,
    UPDATE_TYPES.BLOG,
    UPDATE_TYPES.FORM,
    UPDATE_TYPES.IDENTIFIER,
    UPDATE_TYPES.PIN,
    UPDATE_TYPES.REMOVE,
    UPDATE_TYPES.MENU_ITEM,
    UPDATE_TYPES.DELEGATION,
    UPDATE_TYPES.WALLET_ADDRESS,
    UPDATE_TYPES.PROMOTION,
    UPDATE_TYPES.FEATURED,
  ],
  supposed_updates: [
    {
      update_type: UPDATE_TYPES.RATING,
      values: ["Overall"],
    },
    {
      update_type: UPDATE_TYPES.TAG_CATEGORY,
      values: ["Pros","Cons"],
    },
  ],
};
