import { UPDATE_TYPES } from '../update-registry/update-types';
import { OBJECT_TYPES } from './object-types';
import { ObjectTypeDefinition } from './types';

export const NEWSFEED_OBJECT_TYPE: ObjectTypeDefinition = {
  object_type: OBJECT_TYPES.NEWSFEED,
  supported_updates: [
    UPDATE_TYPES.NAME,
    UPDATE_TYPES.AVATAR,
    UPDATE_TYPES.TITLE,
    UPDATE_TYPES.BACKGROUND,
    UPDATE_TYPES.STATUS,
    UPDATE_TYPES.NEWS_FEED,
    UPDATE_TYPES.PARENT,
    UPDATE_TYPES.DESCRIPTION,
    UPDATE_TYPES.TAG_CATEGORY,
    UPDATE_TYPES.CATEGORY_ITEM,
    UPDATE_TYPES.GALLERY_ALBUM,
    UPDATE_TYPES.GALLERY_ITEM,
    UPDATE_TYPES.WEBSITE,
    UPDATE_TYPES.PIN,
    UPDATE_TYPES.REMOVE,
    UPDATE_TYPES.DELEGATION,
    UPDATE_TYPES.PROMOTION,
    UPDATE_TYPES.CONTENT_VIEW,
  ],
  supposed_updates: [
  ],
};
