export const OBJECT_TYPES = {
  HASHTAG: 'hashtag',
  CRYPTO: 'crypto',
  COMMODITY: 'commodity',
  CURRENCY: 'currency',
  STOCKS: 'stocks',
  INDICES: 'indices',
  APP: 'app',
  LIST: 'list',
  CURRENCIES: 'currencies',
  PRODUCT: 'product',
  DRINK: 'drink',
  PLACE: 'place',
  BUSINESS: 'business',
  CAR: 'car',
  PAGE: 'page',
  SERVICE: 'service',
  COMPANY: 'company',
  ORGANIZATION: 'organization',
  PERSON: 'person',
  HOTEL: 'hotel',
  MOTEL: 'motel',
  RESORT: 'resort',
  BANDB: 'b&b',
  RESTAURANT: 'restaurant',
  DISH: 'dish',
  CRYPTOPAIRS: 'cryptopairs',
  BOOK: 'book',
  WIDGET: 'widget',
  NEWSFEED: 'newsfeed',
  SHOP: 'shop',
  AFFILIATE: 'affiliate',
  WEBPAGE: 'webpage',
  MAP: 'map',
  LINK: 'link',
  RECIPE: 'recipe',
  GROUP: 'group',
  HTML: 'html',
} as const;

export type ObjectType = (typeof OBJECT_TYPES)[keyof typeof OBJECT_TYPES];