import { UPDATE_TYPES } from '../../update-registry/update-types';
import { OBJECT_TYPES } from '../object-types';
import { ObjectTypeDefinition } from '../types';

export const MAP_OBJECT_TYPE: ObjectTypeDefinition = {
  object_type: OBJECT_TYPES.MAP,
  description: 'Map view with objects and layers.',
  supported_updates: [
    UPDATE_TYPES.STATUS,
    UPDATE_TYPES.IMAGE,
    UPDATE_TYPES.PIN,
    UPDATE_TYPES.REMOVE,
    UPDATE_TYPES.NAME,
    UPDATE_TYPES.TITLE,
    UPDATE_TYPES.DESCRIPTION,
    UPDATE_TYPES.IMAGE_BACKGROUND,
    UPDATE_TYPES.MAP_RECTANGLES,
    UPDATE_TYPES.MAP_OBJECT_TYPES,
    UPDATE_TYPES.MAP_OBJECT_TAGS,
    UPDATE_TYPES.MAP_MOBILE_VIEW,
    UPDATE_TYPES.MAP_DESKTOP_VIEW,
    UPDATE_TYPES.MAP_OBJECTS_LIST,
    UPDATE_TYPES.IMAGE_GALLERY,
    UPDATE_TYPES.IMAGE_GALLERY_ITEM,
    UPDATE_TYPES.TAG_CATEGORY,
    UPDATE_TYPES.TAG_CATEGORY_ITEM,
    UPDATE_TYPES.WEBSITE,
    UPDATE_TYPES.DELEGATION,
    UPDATE_TYPES.PROMOTION,
  ],
  supposed_updates: [
  ],
};
