import { UPDATE_TYPES } from '../../update-registry/update-types';
import { OBJECT_TYPES } from '../object-types';
import { ObjectTypeDefinition } from '../types';

export const PLACE_OBJECT_TYPE: ObjectTypeDefinition = {
  object_type: OBJECT_TYPES.PLACE,
  description: 'Place or location with address and geo.',
  supported_updates: [
    UPDATE_TYPES.STATUS,
    UPDATE_TYPES.IMAGE,
    UPDATE_TYPES.NAME,
    UPDATE_TYPES.TITLE,
    UPDATE_TYPES.IMAGE_BACKGROUND,
    UPDATE_TYPES.PARENT,
    UPDATE_TYPES.TAG_CATEGORY,
    UPDATE_TYPES.TAG_CATEGORY_ITEM,
    UPDATE_TYPES.IMAGE_GALLERY,
    UPDATE_TYPES.IMAGE_GALLERY_ITEM,
    UPDATE_TYPES.LIST_ITEM,
    UPDATE_TYPES.BUTTON,
    UPDATE_TYPES.NEWS_FILTER,
    UPDATE_TYPES.SORT_CUSTOM,
    UPDATE_TYPES.AGGREGATE_RATING,
    UPDATE_TYPES.PRICE,
    UPDATE_TYPES.DESCRIPTION,
    UPDATE_TYPES.WORK_HOURS,
    UPDATE_TYPES.ADDRESS,
    UPDATE_TYPES.GEO,
    UPDATE_TYPES.WEBSITE,
    UPDATE_TYPES.TELEPHONE,
    UPDATE_TYPES.EMAIL,
    UPDATE_TYPES.LINK,
    UPDATE_TYPES.FORM,
    UPDATE_TYPES.IDENTIFIER,
    UPDATE_TYPES.PIN,
    UPDATE_TYPES.REMOVE,
    UPDATE_TYPES.MENU_ITEM,
    UPDATE_TYPES.DELEGATION,
    UPDATE_TYPES.WALLET_ADDRESS,
    UPDATE_TYPES.PROMOTION,
  ],
  supposed_updates: [
    {
      update_type: UPDATE_TYPES.AGGREGATE_RATING,
      values: ["Overall"],
    },
    {
      update_type: UPDATE_TYPES.TAG_CATEGORY,
      values: ["Pros","Cons"],
    },
  ],
};
