/**
 * Human-readable titles for left-rail blocks keyed by ODL `update_type`.
 * Uses literal strings aligned with {@link libs/core/src/update-registry/update-types.ts}.
 * Client bundles: prefer registry subpaths over the core barrel for tree-shaking
 * (`@opden-data-layer/core/update-registry`, etc.).
 *
 * @see scripts/migrate-mongo-to-pg/objects/field-name-map.ts
 */

/** Labels keyed by `update_type` string for blocks tied to registry entries. */
const UPDATE_TYPE_TO_LABEL: Record<string, string> = {
  name: 'Name',
  title: 'Title',
  image: 'Avatar',
  imageBackground: 'Background',
  status: 'Status',
  compareAtPrice: 'Compare-at Price',
  saleEvent: 'Sale',
  size: 'Size',
  brand: 'Brand',
  manufacturer: 'Manufacturer',
  merchant: 'Merchant',
  featureList: 'Features',
  category: 'Categories',
  calories: 'Calories',
  budget: 'Budget',
  cookTime: 'Cooking time',
  ingredients: 'Ingredients',
  nutrition: 'Macros',
  author: 'Author',
  publisher: 'Publisher',
  datePublished: 'Published',
  inLanguage: 'Language',
  typicalAgeRange: 'Age Range',
  printLength: 'Print length',
  description: 'Description',
  button: 'Buttons',
  aggregateRating: 'Ratings',
  tagCategory: 'Tag Category',
  tagCategoryItem: 'Tag',
  imageGallery: 'Gallery',
  imageGalleryItem: 'Gallery item',
  price: 'Price',
  option: 'Option',
  workHours: 'Hours',
  address: 'Address',
  geo: 'Map',
  website: 'Website',
  productWeight: 'Weight',
  parent: 'Parent',
  link: 'Social Links',
  telephone: 'Phone',
  email: 'Email',
  walletAddress: 'Wallet',
  identifier: 'Identifier',
  productGroupId: 'Product Group ID',
  menuItem: 'Menu',
  sortCustom: 'List sorting',
  promotion: 'Promotion',
  pin: 'Pin',
  remove: 'Remove',
  delegation: 'Delegation',
  pageContent: 'Page content',
  legalText: 'Legal text',
  license: 'License',
  compatibility: 'Compatibility',
  metadata: 'Metadata',
  allowedTools: 'Allowed tools',
  references: 'References',
};

/** Labels for blocks keyed by internal rail kind (not always 1:1 with update_type). */
export const OBJECT_LEFT_RAIL_BLOCK_LABEL: Record<string, string> = {
  name: 'Name',
  title: 'Title',
  image: 'Avatar',
  imageBackground: 'Background',
  status: 'Status',
  compareAtPrice: 'Compare-at Price',
  saleEvent: 'Sale',
  size: 'Size',
  brand: 'Brand',
  manufacturer: 'Manufacturer',
  merchant: 'Merchant',
  featureList: 'Features',
  category: 'Categories',
  calories: 'Calories',
  budget: 'Budget',
  cookTime: 'Cooking time',
  ingredients: 'Ingredients',
  nutrition: 'Macros',
  author: 'Author',
  publisher: 'Publisher',
  datePublished: 'Published',
  inLanguage: 'Language',
  typicalAgeRange: 'Age Range',
  printLength: 'Print length',
  menuItems: 'Menu',
  description: 'Description',
  button: 'Buttons',
  rating: 'Ratings',
  tags: 'Tags',
  gallery: 'Gallery',
  price: 'Price',
  options: 'Options',
  workHours: 'Hours',
  address: 'Address',
  geo: 'Map',
  websites: 'Website',
  productWeight: 'Weight',
  parent: 'Parent',
  link: 'Social Links',
  phones: 'Phone',
  email: 'Email',
  walletAddress: 'Wallet',
  identifier: 'Identifier',
  productGroupId: 'Product Group ID',
  sortCustom: 'List sorting',
  promotion: 'Promotion',
  pin: 'Pin',
  remove: 'Remove',
  delegation: 'Delegation',
  license: 'License',
  compatibility: 'Compatibility',
  metadata: 'Metadata',
  allowedTools: 'Allowed tools',
  references: 'References',
  objectControl: 'Object Control',
  admins: 'Administrators',
  moderators: 'Moderators',
  trusted: 'Trusted accounts',
  authorities: 'Authorities',
  whitelist: 'Whitelist',
  restricted: 'Restricted',
  banned: 'Banned',
  inheritsFrom: 'Inherits From',
  validityCutoff: 'Validity Cutoff',
};

export function labelForUpdateType(updateType: string): string {
  return UPDATE_TYPE_TO_LABEL[updateType] ?? humanizeUpdateType(updateType);
}

function humanizeUpdateType(updateType: string): string {
  if (!updateType.length) {
    return updateType;
  }
  const spaced = updateType.replace(/([a-z])([A-Z])/g, '$1 $2');
  return spaced.slice(0, 1).toUpperCase() + spaced.slice(1);
}
