export type {
  JsonValue,
  AccountCurrent,
  AccountCurrentUpdate,
  NewAccountCurrent,
  NewObjectUpdate,
  NewObjectsCore,
  NewRankVote,
  NewValidityVote,
  ObjectAuthority,
  ObjectAuthorityUpdate,
  NewObjectAuthority,
  ObjectUpdate,
  ObjectUpdateUpdate,
  ObjectsCore,
  ObjectsCoreUpdate,
  RankVote,
  RankVoteUpdate,
  ValidityVote,
  ValidityVoteUpdate,
} from './odl/tables';
export type { OdlDatabase } from './odl/database';